project:
  type: website
  output-dir: "docs"

website:
  title: "Chris L. Barker"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "CV"
        file: CV.qmd
      - text: "Publications and Working Papers"
        file: Publications.qmd
    right:
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css

editor: visual

